// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/ezdeploy/models"
)

// CreateServiceCreatedCode is the HTTP code returned for type CreateServiceCreated
const CreateServiceCreatedCode int = 201

/*CreateServiceCreated Create Service Success, return service info.

swagger:response createServiceCreated
*/
type CreateServiceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceInfo `json:"body,omitempty"`
}

// NewCreateServiceCreated creates CreateServiceCreated with default headers values
func NewCreateServiceCreated() *CreateServiceCreated {

	return &CreateServiceCreated{}
}

// WithPayload adds the payload to the create service created response
func (o *CreateServiceCreated) WithPayload(payload *models.ServiceInfo) *CreateServiceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service created response
func (o *CreateServiceCreated) SetPayload(payload *models.ServiceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateServiceForbiddenCode is the HTTP code returned for type CreateServiceForbidden
const CreateServiceForbiddenCode int = 403

/*CreateServiceForbidden Create Service Failed, cause do not have permisssion

swagger:response createServiceForbidden
*/
type CreateServiceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateServiceForbidden creates CreateServiceForbidden with default headers values
func NewCreateServiceForbidden() *CreateServiceForbidden {

	return &CreateServiceForbidden{}
}

// WithPayload adds the payload to the create service forbidden response
func (o *CreateServiceForbidden) WithPayload(payload *models.Error) *CreateServiceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service forbidden response
func (o *CreateServiceForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateServiceConflictCode is the HTTP code returned for type CreateServiceConflict
const CreateServiceConflictCode int = 409

/*CreateServiceConflict Create Service Failed, cause service exist

swagger:response createServiceConflict
*/
type CreateServiceConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateServiceConflict creates CreateServiceConflict with default headers values
func NewCreateServiceConflict() *CreateServiceConflict {

	return &CreateServiceConflict{}
}

// WithPayload adds the payload to the create service conflict response
func (o *CreateServiceConflict) WithPayload(payload *models.Error) *CreateServiceConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service conflict response
func (o *CreateServiceConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateServiceInternalServerErrorCode is the HTTP code returned for type CreateServiceInternalServerError
const CreateServiceInternalServerErrorCode int = 500

/*CreateServiceInternalServerError Server Error

swagger:response createServiceInternalServerError
*/
type CreateServiceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateServiceInternalServerError creates CreateServiceInternalServerError with default headers values
func NewCreateServiceInternalServerError() *CreateServiceInternalServerError {

	return &CreateServiceInternalServerError{}
}

// WithPayload adds the payload to the create service internal server error response
func (o *CreateServiceInternalServerError) WithPayload(payload *models.Error) *CreateServiceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service internal server error response
func (o *CreateServiceInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
