// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ez-deploy/ezdeploy/models"
)

// CreateServiceHandlerFunc turns a function with the right signature into a create service handler
type CreateServiceHandlerFunc func(CreateServiceParams, *models.AuthInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateServiceHandlerFunc) Handle(params CreateServiceParams, principal *models.AuthInfo) middleware.Responder {
	return fn(params, principal)
}

// CreateServiceHandler interface for that can handle valid create service params
type CreateServiceHandler interface {
	Handle(CreateServiceParams, *models.AuthInfo) middleware.Responder
}

// NewCreateService creates a new http.Handler for the create service operation
func NewCreateService(ctx *middleware.Context, handler CreateServiceHandler) *CreateService {
	return &CreateService{Context: ctx, Handler: handler}
}

/* CreateService swagger:route POST /service/create Service createService

Create Service

*/
type CreateService struct {
	Context *middleware.Context
	Handler CreateServiceHandler
}

func (o *CreateService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.AuthInfo
	if uprinc != nil {
		principal = uprinc.(*models.AuthInfo) // this is really a models.AuthInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
