// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/ezdeploy/models"
)

// DeleteServiceOKCode is the HTTP code returned for type DeleteServiceOK
const DeleteServiceOKCode int = 200

/*DeleteServiceOK Delete Service Success, return service info.

swagger:response deleteServiceOK
*/
type DeleteServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceInfo `json:"body,omitempty"`
}

// NewDeleteServiceOK creates DeleteServiceOK with default headers values
func NewDeleteServiceOK() *DeleteServiceOK {

	return &DeleteServiceOK{}
}

// WithPayload adds the payload to the delete service o k response
func (o *DeleteServiceOK) WithPayload(payload *models.ServiceInfo) *DeleteServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service o k response
func (o *DeleteServiceOK) SetPayload(payload *models.ServiceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServiceForbiddenCode is the HTTP code returned for type DeleteServiceForbidden
const DeleteServiceForbiddenCode int = 403

/*DeleteServiceForbidden Delete Service Failed, cause do not have permisssion

swagger:response deleteServiceForbidden
*/
type DeleteServiceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteServiceForbidden creates DeleteServiceForbidden with default headers values
func NewDeleteServiceForbidden() *DeleteServiceForbidden {

	return &DeleteServiceForbidden{}
}

// WithPayload adds the payload to the delete service forbidden response
func (o *DeleteServiceForbidden) WithPayload(payload *models.Error) *DeleteServiceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service forbidden response
func (o *DeleteServiceForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteServiceInternalServerErrorCode is the HTTP code returned for type DeleteServiceInternalServerError
const DeleteServiceInternalServerErrorCode int = 500

/*DeleteServiceInternalServerError Server Error

swagger:response deleteServiceInternalServerError
*/
type DeleteServiceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteServiceInternalServerError creates DeleteServiceInternalServerError with default headers values
func NewDeleteServiceInternalServerError() *DeleteServiceInternalServerError {

	return &DeleteServiceInternalServerError{}
}

// WithPayload adds the payload to the delete service internal server error response
func (o *DeleteServiceInternalServerError) WithPayload(payload *models.Error) *DeleteServiceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete service internal server error response
func (o *DeleteServiceInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteServiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
