// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/ezdeploy/models"
)

// ListServiceOKCode is the HTTP code returned for type ListServiceOK
const ListServiceOKCode int = 200

/*ListServiceOK List All Services Success, return service info. (service name, service id, service description)

swagger:response listServiceOK
*/
type ListServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceInfo `json:"body,omitempty"`
}

// NewListServiceOK creates ListServiceOK with default headers values
func NewListServiceOK() *ListServiceOK {

	return &ListServiceOK{}
}

// WithPayload adds the payload to the list service o k response
func (o *ListServiceOK) WithPayload(payload *models.ServiceInfo) *ListServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service o k response
func (o *ListServiceOK) SetPayload(payload *models.ServiceInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceForbiddenCode is the HTTP code returned for type ListServiceForbidden
const ListServiceForbiddenCode int = 403

/*ListServiceForbidden List Service Failed, cause do not have permisssion

swagger:response listServiceForbidden
*/
type ListServiceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListServiceForbidden creates ListServiceForbidden with default headers values
func NewListServiceForbidden() *ListServiceForbidden {

	return &ListServiceForbidden{}
}

// WithPayload adds the payload to the list service forbidden response
func (o *ListServiceForbidden) WithPayload(payload *models.Error) *ListServiceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service forbidden response
func (o *ListServiceForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListServiceInternalServerErrorCode is the HTTP code returned for type ListServiceInternalServerError
const ListServiceInternalServerErrorCode int = 500

/*ListServiceInternalServerError Server Error

swagger:response listServiceInternalServerError
*/
type ListServiceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListServiceInternalServerError creates ListServiceInternalServerError with default headers values
func NewListServiceInternalServerError() *ListServiceInternalServerError {

	return &ListServiceInternalServerError{}
}

// WithPayload adds the payload to the list service internal server error response
func (o *ListServiceInternalServerError) WithPayload(payload *models.Error) *ListServiceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list service internal server error response
func (o *ListServiceInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListServiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
