// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ez-deploy/ezdeploy/models"
)

// ListServiceHandlerFunc turns a function with the right signature into a list service handler
type ListServiceHandlerFunc func(ListServiceParams, *models.AuthInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn ListServiceHandlerFunc) Handle(params ListServiceParams, principal *models.AuthInfo) middleware.Responder {
	return fn(params, principal)
}

// ListServiceHandler interface for that can handle valid list service params
type ListServiceHandler interface {
	Handle(ListServiceParams, *models.AuthInfo) middleware.Responder
}

// NewListService creates a new http.Handler for the list service operation
func NewListService(ctx *middleware.Context, handler ListServiceHandler) *ListService {
	return &ListService{Context: ctx, Handler: handler}
}

/* ListService swagger:route GET /service/list Service listService

List Service by project ID, service ID, service name.

*/
type ListService struct {
	Context *middleware.Context
	Handler ListServiceHandler
}

func (o *ListService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.AuthInfo
	if uprinc != nil {
		principal = uprinc.(*models.AuthInfo) // this is really a models.AuthInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
