// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ez-deploy/ezdeploy/models"
)

// ListServiceVersionHandlerFunc turns a function with the right signature into a list service version handler
type ListServiceVersionHandlerFunc func(ListServiceVersionParams, *models.AuthInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn ListServiceVersionHandlerFunc) Handle(params ListServiceVersionParams, principal *models.AuthInfo) middleware.Responder {
	return fn(params, principal)
}

// ListServiceVersionHandler interface for that can handle valid list service version params
type ListServiceVersionHandler interface {
	Handle(ListServiceVersionParams, *models.AuthInfo) middleware.Responder
}

// NewListServiceVersion creates a new http.Handler for the list service version operation
func NewListServiceVersion(ctx *middleware.Context, handler ListServiceVersionHandler) *ListServiceVersion {
	return &ListServiceVersion{Context: ctx, Handler: handler}
}

/* ListServiceVersion swagger:route GET /service/version/list Service listServiceVersion

List Service Version by service ID.

*/
type ListServiceVersion struct {
	Context *middleware.Context
	Handler ListServiceVersionHandler
}

func (o *ListServiceVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListServiceVersionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.AuthInfo
	if uprinc != nil {
		principal = uprinc.(*models.AuthInfo) // this is really a models.AuthInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
