// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ez-deploy/ezdeploy/models"
)

// UpdateServiceDescriptionHandlerFunc turns a function with the right signature into a update service description handler
type UpdateServiceDescriptionHandlerFunc func(UpdateServiceDescriptionParams, *models.AuthInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateServiceDescriptionHandlerFunc) Handle(params UpdateServiceDescriptionParams, principal *models.AuthInfo) middleware.Responder {
	return fn(params, principal)
}

// UpdateServiceDescriptionHandler interface for that can handle valid update service description params
type UpdateServiceDescriptionHandler interface {
	Handle(UpdateServiceDescriptionParams, *models.AuthInfo) middleware.Responder
}

// NewUpdateServiceDescription creates a new http.Handler for the update service description operation
func NewUpdateServiceDescription(ctx *middleware.Context, handler UpdateServiceDescriptionHandler) *UpdateServiceDescription {
	return &UpdateServiceDescription{Context: ctx, Handler: handler}
}

/* UpdateServiceDescription swagger:route PUT /service/update/desc Service updateServiceDescription

Update Service Description

*/
type UpdateServiceDescription struct {
	Context *middleware.Context
	Handler UpdateServiceDescriptionHandler
}

func (o *UpdateServiceDescription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateServiceDescriptionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.AuthInfo
	if uprinc != nil {
		principal = uprinc.(*models.AuthInfo) // this is really a models.AuthInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
