// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ez-deploy/ezdeploy/models"
)

// UpdateServiceVersionHandlerFunc turns a function with the right signature into a update service version handler
type UpdateServiceVersionHandlerFunc func(UpdateServiceVersionParams, *models.AuthInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateServiceVersionHandlerFunc) Handle(params UpdateServiceVersionParams, principal *models.AuthInfo) middleware.Responder {
	return fn(params, principal)
}

// UpdateServiceVersionHandler interface for that can handle valid update service version params
type UpdateServiceVersionHandler interface {
	Handle(UpdateServiceVersionParams, *models.AuthInfo) middleware.Responder
}

// NewUpdateServiceVersion creates a new http.Handler for the update service version operation
func NewUpdateServiceVersion(ctx *middleware.Context, handler UpdateServiceVersionHandler) *UpdateServiceVersion {
	return &UpdateServiceVersion{Context: ctx, Handler: handler}
}

/* UpdateServiceVersion swagger:route PUT /service/update/deploy Service updateServiceVersion

Update Service Version

*/
type UpdateServiceVersion struct {
	Context *middleware.Context
	Handler UpdateServiceVersionHandler
}

func (o *UpdateServiceVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateServiceVersionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.AuthInfo
	if uprinc != nil {
		principal = uprinc.(*models.AuthInfo) // this is really a models.AuthInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
