// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ez-deploy/ezdeploy/client/identity"
	"github.com/ez-deploy/ezdeploy/client/pod"
	"github.com/ez-deploy/ezdeploy/client/project"
	"github.com/ez-deploy/ezdeploy/client/r_b_a_c"
	"github.com/ez-deploy/ezdeploy/client/service"
)

// Default ez deploy apiserver HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new ez deploy apiserver HTTP client.
func NewHTTPClient(formats strfmt.Registry) *EzDeployApiserver {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new ez deploy apiserver HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *EzDeployApiserver {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new ez deploy apiserver client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *EzDeployApiserver {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(EzDeployApiserver)
	cli.Transport = transport
	cli.Identity = identity.New(transport, formats)
	cli.Pod = pod.New(transport, formats)
	cli.Project = project.New(transport, formats)
	cli.Rbac = r_b_a_c.New(transport, formats)
	cli.Service = service.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// EzDeployApiserver is a client for ez deploy apiserver
type EzDeployApiserver struct {
	Identity identity.ClientService

	Pod pod.ClientService

	Project project.ClientService

	Rbac r_b_a_c.ClientService

	Service service.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *EzDeployApiserver) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Identity.SetTransport(transport)
	c.Pod.SetTransport(transport)
	c.Project.SetTransport(transport)
	c.Rbac.SetTransport(transport)
	c.Service.SetTransport(transport)
}
