// Code generated by go-swagger; DO NOT EDIT.

package pod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ez-deploy/ezdeploy/models"
)

// CreatePodTicketReader is a Reader for the CreatePodTicket structure.
type CreatePodTicketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePodTicketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreatePodTicketCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreatePodTicketForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreatePodTicketInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreatePodTicketCreated creates a CreatePodTicketCreated with default headers values
func NewCreatePodTicketCreated() *CreatePodTicketCreated {
	return &CreatePodTicketCreated{}
}

/* CreatePodTicketCreated describes a response with status code 201, with default header values.

Create Pod Ticket Success, return pod ticket info.
*/
type CreatePodTicketCreated struct {
	Payload *models.SSHPodTicket
}

func (o *CreatePodTicketCreated) Error() string {
	return fmt.Sprintf("[POST /visit/pod/ticket/create][%d] createPodTicketCreated  %+v", 201, o.Payload)
}
func (o *CreatePodTicketCreated) GetPayload() *models.SSHPodTicket {
	return o.Payload
}

func (o *CreatePodTicketCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SSHPodTicket)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePodTicketForbidden creates a CreatePodTicketForbidden with default headers values
func NewCreatePodTicketForbidden() *CreatePodTicketForbidden {
	return &CreatePodTicketForbidden{}
}

/* CreatePodTicketForbidden describes a response with status code 403, with default header values.

Create Pod Ticket Failed, cause do not have permisssion
*/
type CreatePodTicketForbidden struct {
	Payload *models.Error
}

func (o *CreatePodTicketForbidden) Error() string {
	return fmt.Sprintf("[POST /visit/pod/ticket/create][%d] createPodTicketForbidden  %+v", 403, o.Payload)
}
func (o *CreatePodTicketForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreatePodTicketForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePodTicketInternalServerError creates a CreatePodTicketInternalServerError with default headers values
func NewCreatePodTicketInternalServerError() *CreatePodTicketInternalServerError {
	return &CreatePodTicketInternalServerError{}
}

/* CreatePodTicketInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type CreatePodTicketInternalServerError struct {
	Payload *models.Error
}

func (o *CreatePodTicketInternalServerError) Error() string {
	return fmt.Sprintf("[POST /visit/pod/ticket/create][%d] createPodTicketInternalServerError  %+v", 500, o.Payload)
}
func (o *CreatePodTicketInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreatePodTicketInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreatePodTicketBody create pod ticket body
swagger:model CreatePodTicketBody
*/
type CreatePodTicketBody struct {

	// pod name
	PodName string `json:"pod_name,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`
}

// Validate validates this create pod ticket body
func (o *CreatePodTicketBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create pod ticket body based on context it is used
func (o *CreatePodTicketBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePodTicketBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePodTicketBody) UnmarshalBinary(b []byte) error {
	var res CreatePodTicketBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
