// Code generated by go-swagger; DO NOT EDIT.

package pod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreatePodTicketParams creates a new CreatePodTicketParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePodTicketParams() *CreatePodTicketParams {
	return &CreatePodTicketParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePodTicketParamsWithTimeout creates a new CreatePodTicketParams object
// with the ability to set a timeout on a request.
func NewCreatePodTicketParamsWithTimeout(timeout time.Duration) *CreatePodTicketParams {
	return &CreatePodTicketParams{
		timeout: timeout,
	}
}

// NewCreatePodTicketParamsWithContext creates a new CreatePodTicketParams object
// with the ability to set a context for a request.
func NewCreatePodTicketParamsWithContext(ctx context.Context) *CreatePodTicketParams {
	return &CreatePodTicketParams{
		Context: ctx,
	}
}

// NewCreatePodTicketParamsWithHTTPClient creates a new CreatePodTicketParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePodTicketParamsWithHTTPClient(client *http.Client) *CreatePodTicketParams {
	return &CreatePodTicketParams{
		HTTPClient: client,
	}
}

/* CreatePodTicketParams contains all the parameters to send to the API endpoint
   for the create pod ticket operation.

   Typically these are written to a http.Request.
*/
type CreatePodTicketParams struct {

	// Body.
	Body CreatePodTicketBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create pod ticket params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePodTicketParams) WithDefaults() *CreatePodTicketParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create pod ticket params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePodTicketParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create pod ticket params
func (o *CreatePodTicketParams) WithTimeout(timeout time.Duration) *CreatePodTicketParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create pod ticket params
func (o *CreatePodTicketParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create pod ticket params
func (o *CreatePodTicketParams) WithContext(ctx context.Context) *CreatePodTicketParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create pod ticket params
func (o *CreatePodTicketParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create pod ticket params
func (o *CreatePodTicketParams) WithHTTPClient(client *http.Client) *CreatePodTicketParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create pod ticket params
func (o *CreatePodTicketParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create pod ticket params
func (o *CreatePodTicketParams) WithBody(body CreatePodTicketBody) *CreatePodTicketParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create pod ticket params
func (o *CreatePodTicketParams) SetBody(body CreatePodTicketBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePodTicketParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
