// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ez-deploy/ezdeploy/models"
)

// CreateServiceVersionReader is a Reader for the CreateServiceVersion structure.
type CreateServiceVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServiceVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateServiceVersionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateServiceVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateServiceVersionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateServiceVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateServiceVersionCreated creates a CreateServiceVersionCreated with default headers values
func NewCreateServiceVersionCreated() *CreateServiceVersionCreated {
	return &CreateServiceVersionCreated{}
}

/* CreateServiceVersionCreated describes a response with status code 201, with default header values.

Create Service Version Success, return service version info.
*/
type CreateServiceVersionCreated struct {
	Payload *models.ServiceVersion
}

func (o *CreateServiceVersionCreated) Error() string {
	return fmt.Sprintf("[POST /service/version/create][%d] createServiceVersionCreated  %+v", 201, o.Payload)
}
func (o *CreateServiceVersionCreated) GetPayload() *models.ServiceVersion {
	return o.Payload
}

func (o *CreateServiceVersionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceVersionForbidden creates a CreateServiceVersionForbidden with default headers values
func NewCreateServiceVersionForbidden() *CreateServiceVersionForbidden {
	return &CreateServiceVersionForbidden{}
}

/* CreateServiceVersionForbidden describes a response with status code 403, with default header values.

Create Service Version Failed, cause do not have permisssion
*/
type CreateServiceVersionForbidden struct {
	Payload *models.Error
}

func (o *CreateServiceVersionForbidden) Error() string {
	return fmt.Sprintf("[POST /service/version/create][%d] createServiceVersionForbidden  %+v", 403, o.Payload)
}
func (o *CreateServiceVersionForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateServiceVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceVersionConflict creates a CreateServiceVersionConflict with default headers values
func NewCreateServiceVersionConflict() *CreateServiceVersionConflict {
	return &CreateServiceVersionConflict{}
}

/* CreateServiceVersionConflict describes a response with status code 409, with default header values.

Create Service Version Failed, cause service version exist
*/
type CreateServiceVersionConflict struct {
	Payload *models.Error
}

func (o *CreateServiceVersionConflict) Error() string {
	return fmt.Sprintf("[POST /service/version/create][%d] createServiceVersionConflict  %+v", 409, o.Payload)
}
func (o *CreateServiceVersionConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateServiceVersionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceVersionInternalServerError creates a CreateServiceVersionInternalServerError with default headers values
func NewCreateServiceVersionInternalServerError() *CreateServiceVersionInternalServerError {
	return &CreateServiceVersionInternalServerError{}
}

/* CreateServiceVersionInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type CreateServiceVersionInternalServerError struct {
	Payload *models.Error
}

func (o *CreateServiceVersionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /service/version/create][%d] createServiceVersionInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateServiceVersionInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateServiceVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
