// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ez-deploy/ezdeploy/models"
)

// NewCreateServiceVersionParams creates a new CreateServiceVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateServiceVersionParams() *CreateServiceVersionParams {
	return &CreateServiceVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateServiceVersionParamsWithTimeout creates a new CreateServiceVersionParams object
// with the ability to set a timeout on a request.
func NewCreateServiceVersionParamsWithTimeout(timeout time.Duration) *CreateServiceVersionParams {
	return &CreateServiceVersionParams{
		timeout: timeout,
	}
}

// NewCreateServiceVersionParamsWithContext creates a new CreateServiceVersionParams object
// with the ability to set a context for a request.
func NewCreateServiceVersionParamsWithContext(ctx context.Context) *CreateServiceVersionParams {
	return &CreateServiceVersionParams{
		Context: ctx,
	}
}

// NewCreateServiceVersionParamsWithHTTPClient creates a new CreateServiceVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateServiceVersionParamsWithHTTPClient(client *http.Client) *CreateServiceVersionParams {
	return &CreateServiceVersionParams{
		HTTPClient: client,
	}
}

/* CreateServiceVersionParams contains all the parameters to send to the API endpoint
   for the create service version operation.

   Typically these are written to a http.Request.
*/
type CreateServiceVersionParams struct {

	// Body.
	Body *models.ServiceVersion

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create service version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateServiceVersionParams) WithDefaults() *CreateServiceVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create service version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateServiceVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create service version params
func (o *CreateServiceVersionParams) WithTimeout(timeout time.Duration) *CreateServiceVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create service version params
func (o *CreateServiceVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create service version params
func (o *CreateServiceVersionParams) WithContext(ctx context.Context) *CreateServiceVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create service version params
func (o *CreateServiceVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create service version params
func (o *CreateServiceVersionParams) WithHTTPClient(client *http.Client) *CreateServiceVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create service version params
func (o *CreateServiceVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create service version params
func (o *CreateServiceVersionParams) WithBody(body *models.ServiceVersion) *CreateServiceVersionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create service version params
func (o *CreateServiceVersionParams) SetBody(body *models.ServiceVersion) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateServiceVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
