// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListServiceVersionParams creates a new ListServiceVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListServiceVersionParams() *ListServiceVersionParams {
	return &ListServiceVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListServiceVersionParamsWithTimeout creates a new ListServiceVersionParams object
// with the ability to set a timeout on a request.
func NewListServiceVersionParamsWithTimeout(timeout time.Duration) *ListServiceVersionParams {
	return &ListServiceVersionParams{
		timeout: timeout,
	}
}

// NewListServiceVersionParamsWithContext creates a new ListServiceVersionParams object
// with the ability to set a context for a request.
func NewListServiceVersionParamsWithContext(ctx context.Context) *ListServiceVersionParams {
	return &ListServiceVersionParams{
		Context: ctx,
	}
}

// NewListServiceVersionParamsWithHTTPClient creates a new ListServiceVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewListServiceVersionParamsWithHTTPClient(client *http.Client) *ListServiceVersionParams {
	return &ListServiceVersionParams{
		HTTPClient: client,
	}
}

/* ListServiceVersionParams contains all the parameters to send to the API endpoint
   for the list service version operation.

   Typically these are written to a http.Request.
*/
type ListServiceVersionParams struct {

	// ServiceID.
	ServiceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list service version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListServiceVersionParams) WithDefaults() *ListServiceVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list service version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListServiceVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list service version params
func (o *ListServiceVersionParams) WithTimeout(timeout time.Duration) *ListServiceVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list service version params
func (o *ListServiceVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list service version params
func (o *ListServiceVersionParams) WithContext(ctx context.Context) *ListServiceVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list service version params
func (o *ListServiceVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list service version params
func (o *ListServiceVersionParams) WithHTTPClient(client *http.Client) *ListServiceVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list service version params
func (o *ListServiceVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServiceID adds the serviceID to the list service version params
func (o *ListServiceVersionParams) WithServiceID(serviceID int64) *ListServiceVersionParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the list service version params
func (o *ListServiceVersionParams) SetServiceID(serviceID int64) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ListServiceVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param service_id
	qrServiceID := o.ServiceID
	qServiceID := swag.FormatInt64(qrServiceID)
	if qServiceID != "" {

		if err := r.SetQueryParam("service_id", qServiceID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
