// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ez-deploy/ezdeploy/models"
)

// ListServiceReader is a Reader for the ListService structure.
type ListServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewListServiceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListServiceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListServiceOK creates a ListServiceOK with default headers values
func NewListServiceOK() *ListServiceOK {
	return &ListServiceOK{}
}

/* ListServiceOK describes a response with status code 200, with default header values.

List All Services Success, return service info. (service name, service id, service description)
*/
type ListServiceOK struct {
	Payload *ListServiceOKBody
}

func (o *ListServiceOK) Error() string {
	return fmt.Sprintf("[GET /service/list][%d] listServiceOK  %+v", 200, o.Payload)
}
func (o *ListServiceOK) GetPayload() *ListServiceOKBody {
	return o.Payload
}

func (o *ListServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListServiceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServiceForbidden creates a ListServiceForbidden with default headers values
func NewListServiceForbidden() *ListServiceForbidden {
	return &ListServiceForbidden{}
}

/* ListServiceForbidden describes a response with status code 403, with default header values.

List Service Failed, cause do not have permisssion
*/
type ListServiceForbidden struct {
	Payload *models.Error
}

func (o *ListServiceForbidden) Error() string {
	return fmt.Sprintf("[GET /service/list][%d] listServiceForbidden  %+v", 403, o.Payload)
}
func (o *ListServiceForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServiceInternalServerError creates a ListServiceInternalServerError with default headers values
func NewListServiceInternalServerError() *ListServiceInternalServerError {
	return &ListServiceInternalServerError{}
}

/* ListServiceInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type ListServiceInternalServerError struct {
	Payload *models.Error
}

func (o *ListServiceInternalServerError) Error() string {
	return fmt.Sprintf("[GET /service/list][%d] listServiceInternalServerError  %+v", 500, o.Payload)
}
func (o *ListServiceInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListServiceOKBody list service o k body
swagger:model ListServiceOKBody
*/
type ListServiceOKBody struct {

	// services
	Services []*models.ServiceInfo `json:"services"`
}

// Validate validates this list service o k body
func (o *ListServiceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateServices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListServiceOKBody) validateServices(formats strfmt.Registry) error {
	if swag.IsZero(o.Services) { // not required
		return nil
	}

	for i := 0; i < len(o.Services); i++ {
		if swag.IsZero(o.Services[i]) { // not required
			continue
		}

		if o.Services[i] != nil {
			if err := o.Services[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listServiceOK" + "." + "services" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("listServiceOK" + "." + "services" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this list service o k body based on the context it is used
func (o *ListServiceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateServices(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListServiceOKBody) contextValidateServices(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Services); i++ {

		if o.Services[i] != nil {
			if err := o.Services[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listServiceOK" + "." + "services" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("listServiceOK" + "." + "services" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListServiceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListServiceOKBody) UnmarshalBinary(b []byte) error {
	var res ListServiceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
