// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ez-deploy/ezdeploy/models"
)

// ListServiceVersionReader is a Reader for the ListServiceVersion structure.
type ListServiceVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServiceVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListServiceVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewListServiceVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListServiceVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListServiceVersionOK creates a ListServiceVersionOK with default headers values
func NewListServiceVersionOK() *ListServiceVersionOK {
	return &ListServiceVersionOK{}
}

/* ListServiceVersionOK describes a response with status code 200, with default header values.

List Service Version Success, return service version info.
*/
type ListServiceVersionOK struct {
	Payload *ListServiceVersionOKBody
}

func (o *ListServiceVersionOK) Error() string {
	return fmt.Sprintf("[GET /service/version/list][%d] listServiceVersionOK  %+v", 200, o.Payload)
}
func (o *ListServiceVersionOK) GetPayload() *ListServiceVersionOKBody {
	return o.Payload
}

func (o *ListServiceVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListServiceVersionOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServiceVersionForbidden creates a ListServiceVersionForbidden with default headers values
func NewListServiceVersionForbidden() *ListServiceVersionForbidden {
	return &ListServiceVersionForbidden{}
}

/* ListServiceVersionForbidden describes a response with status code 403, with default header values.

List Service Version Failed, cause do not have permisssion
*/
type ListServiceVersionForbidden struct {
	Payload *models.Error
}

func (o *ListServiceVersionForbidden) Error() string {
	return fmt.Sprintf("[GET /service/version/list][%d] listServiceVersionForbidden  %+v", 403, o.Payload)
}
func (o *ListServiceVersionForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServiceVersionInternalServerError creates a ListServiceVersionInternalServerError with default headers values
func NewListServiceVersionInternalServerError() *ListServiceVersionInternalServerError {
	return &ListServiceVersionInternalServerError{}
}

/* ListServiceVersionInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type ListServiceVersionInternalServerError struct {
	Payload *models.Error
}

func (o *ListServiceVersionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /service/version/list][%d] listServiceVersionInternalServerError  %+v", 500, o.Payload)
}
func (o *ListServiceVersionInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListServiceVersionOKBody list service version o k body
swagger:model ListServiceVersionOKBody
*/
type ListServiceVersionOKBody struct {

	// versions
	Versions []*models.ServiceVersion `json:"versions"`
}

// Validate validates this list service version o k body
func (o *ListServiceVersionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateVersions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListServiceVersionOKBody) validateVersions(formats strfmt.Registry) error {
	if swag.IsZero(o.Versions) { // not required
		return nil
	}

	for i := 0; i < len(o.Versions); i++ {
		if swag.IsZero(o.Versions[i]) { // not required
			continue
		}

		if o.Versions[i] != nil {
			if err := o.Versions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listServiceVersionOK" + "." + "versions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("listServiceVersionOK" + "." + "versions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this list service version o k body based on the context it is used
func (o *ListServiceVersionOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateVersions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListServiceVersionOKBody) contextValidateVersions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Versions); i++ {

		if o.Versions[i] != nil {
			if err := o.Versions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listServiceVersionOK" + "." + "versions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("listServiceVersionOK" + "." + "versions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListServiceVersionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListServiceVersionOKBody) UnmarshalBinary(b []byte) error {
	var res ListServiceVersionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
