// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ez-deploy/ezdeploy/models"
)

// NewUpdateServiceDescriptionParams creates a new UpdateServiceDescriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateServiceDescriptionParams() *UpdateServiceDescriptionParams {
	return &UpdateServiceDescriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateServiceDescriptionParamsWithTimeout creates a new UpdateServiceDescriptionParams object
// with the ability to set a timeout on a request.
func NewUpdateServiceDescriptionParamsWithTimeout(timeout time.Duration) *UpdateServiceDescriptionParams {
	return &UpdateServiceDescriptionParams{
		timeout: timeout,
	}
}

// NewUpdateServiceDescriptionParamsWithContext creates a new UpdateServiceDescriptionParams object
// with the ability to set a context for a request.
func NewUpdateServiceDescriptionParamsWithContext(ctx context.Context) *UpdateServiceDescriptionParams {
	return &UpdateServiceDescriptionParams{
		Context: ctx,
	}
}

// NewUpdateServiceDescriptionParamsWithHTTPClient creates a new UpdateServiceDescriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateServiceDescriptionParamsWithHTTPClient(client *http.Client) *UpdateServiceDescriptionParams {
	return &UpdateServiceDescriptionParams{
		HTTPClient: client,
	}
}

/* UpdateServiceDescriptionParams contains all the parameters to send to the API endpoint
   for the update service description operation.

   Typically these are written to a http.Request.
*/
type UpdateServiceDescriptionParams struct {

	// Body.
	Body *models.ServiceInfo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update service description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateServiceDescriptionParams) WithDefaults() *UpdateServiceDescriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update service description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateServiceDescriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update service description params
func (o *UpdateServiceDescriptionParams) WithTimeout(timeout time.Duration) *UpdateServiceDescriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service description params
func (o *UpdateServiceDescriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service description params
func (o *UpdateServiceDescriptionParams) WithContext(ctx context.Context) *UpdateServiceDescriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service description params
func (o *UpdateServiceDescriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service description params
func (o *UpdateServiceDescriptionParams) WithHTTPClient(client *http.Client) *UpdateServiceDescriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service description params
func (o *UpdateServiceDescriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update service description params
func (o *UpdateServiceDescriptionParams) WithBody(body *models.ServiceInfo) *UpdateServiceDescriptionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update service description params
func (o *UpdateServiceDescriptionParams) SetBody(body *models.ServiceInfo) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServiceDescriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
