// Code generated by go-swagger; DO NOT EDIT.

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LogoutOKCode is the HTTP code returned for type LogoutOK
const LogoutOKCode int = 200

/*LogoutOK Logout Success

swagger:response logoutOK
*/
type LogoutOK struct {
}

// NewLogoutOK creates LogoutOK with default headers values
func NewLogoutOK() *LogoutOK {

	return &LogoutOK{}
}

// WriteResponse to the client
func (o *LogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// LogoutUnauthorizedCode is the HTTP code returned for type LogoutUnauthorized
const LogoutUnauthorizedCode int = 401

/*LogoutUnauthorized Logout Failed, no login

swagger:response logoutUnauthorized
*/
type LogoutUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewLogoutUnauthorized creates LogoutUnauthorized with default headers values
func NewLogoutUnauthorized() *LogoutUnauthorized {

	return &LogoutUnauthorized{}
}

// WithPayload adds the payload to the logout unauthorized response
func (o *LogoutUnauthorized) WithPayload(payload interface{}) *LogoutUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout unauthorized response
func (o *LogoutUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// LogoutInternalServerErrorCode is the HTTP code returned for type LogoutInternalServerError
const LogoutInternalServerErrorCode int = 500

/*LogoutInternalServerError Server Error

swagger:response logoutInternalServerError
*/
type LogoutInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewLogoutInternalServerError creates LogoutInternalServerError with default headers values
func NewLogoutInternalServerError() *LogoutInternalServerError {

	return &LogoutInternalServerError{}
}

// WithPayload adds the payload to the logout internal server error response
func (o *LogoutInternalServerError) WithPayload(payload interface{}) *LogoutInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout internal server error response
func (o *LogoutInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
