// Code generated by go-swagger; DO NOT EDIT.

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ez-deploy/ezdeploy/models"
)

// WhoamiOKCode is the HTTP code returned for type WhoamiOK
const WhoamiOKCode int = 200

/*WhoamiOK Get Current User's Info Success

swagger:response whoamiOK
*/
type WhoamiOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserInfo `json:"body,omitempty"`
}

// NewWhoamiOK creates WhoamiOK with default headers values
func NewWhoamiOK() *WhoamiOK {

	return &WhoamiOK{}
}

// WithPayload adds the payload to the whoami o k response
func (o *WhoamiOK) WithPayload(payload *models.UserInfo) *WhoamiOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the whoami o k response
func (o *WhoamiOK) SetPayload(payload *models.UserInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WhoamiOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
