// Code generated by go-swagger; DO NOT EDIT.

package r_b_a_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectRBACParams creates a new GetProjectRBACParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectRBACParams() *GetProjectRBACParams {
	return &GetProjectRBACParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectRBACParamsWithTimeout creates a new GetProjectRBACParams object
// with the ability to set a timeout on a request.
func NewGetProjectRBACParamsWithTimeout(timeout time.Duration) *GetProjectRBACParams {
	return &GetProjectRBACParams{
		timeout: timeout,
	}
}

// NewGetProjectRBACParamsWithContext creates a new GetProjectRBACParams object
// with the ability to set a context for a request.
func NewGetProjectRBACParamsWithContext(ctx context.Context) *GetProjectRBACParams {
	return &GetProjectRBACParams{
		Context: ctx,
	}
}

// NewGetProjectRBACParamsWithHTTPClient creates a new GetProjectRBACParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectRBACParamsWithHTTPClient(client *http.Client) *GetProjectRBACParams {
	return &GetProjectRBACParams{
		HTTPClient: client,
	}
}

/* GetProjectRBACParams contains all the parameters to send to the API endpoint
   for the get project r b a c operation.

   Typically these are written to a http.Request.
*/
type GetProjectRBACParams struct {

	/* ID.

	   projectID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project r b a c params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectRBACParams) WithDefaults() *GetProjectRBACParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project r b a c params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectRBACParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project r b a c params
func (o *GetProjectRBACParams) WithTimeout(timeout time.Duration) *GetProjectRBACParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project r b a c params
func (o *GetProjectRBACParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project r b a c params
func (o *GetProjectRBACParams) WithContext(ctx context.Context) *GetProjectRBACParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project r b a c params
func (o *GetProjectRBACParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project r b a c params
func (o *GetProjectRBACParams) WithHTTPClient(client *http.Client) *GetProjectRBACParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project r b a c params
func (o *GetProjectRBACParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get project r b a c params
func (o *GetProjectRBACParams) WithID(id int64) *GetProjectRBACParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project r b a c params
func (o *GetProjectRBACParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectRBACParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
