// Code generated by go-swagger; DO NOT EDIT.

package r_b_a_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new r b a c API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for r b a c API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetProjectRBAC(params *GetProjectRBACParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectRBACOK, error)

	GetUserRBAC(params *GetUserRBACParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetUserRBACOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetProjectRBAC Get Project RBAC
*/
func (a *Client) GetProjectRBAC(params *GetProjectRBACParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetProjectRBACOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetProjectRBACParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetProjectRBAC",
		Method:             "GET",
		PathPattern:        "/rbac/project/get",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProjectRBACReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetProjectRBACOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetProjectRBAC: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetUserRBAC Get User RBAC
*/
func (a *Client) GetUserRBAC(params *GetUserRBACParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetUserRBACOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserRBACParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetUserRBAC",
		Method:             "GET",
		PathPattern:        "/rbac/user/get",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetUserRBACReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUserRBACOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetUserRBAC: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
