// Code generated by go-swagger; DO NOT EDIT.

package r_b_a_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetUserRBACParams creates a new GetUserRBACParams object
//
// There are no default values defined in the spec.
func NewGetUserRBACParams() GetUserRBACParams {

	return GetUserRBACParams{}
}

// GetUserRBACParams contains all the bound params for the get user r b a c operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUserRBAC
type GetUserRBACParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUserRBACParams() beforehand.
func (o *GetUserRBACParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
