// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "apiserver",
    "title": "ez-deploy apiserver.",
    "version": "1.0.0"
  },
  "paths": {
    "/user/create": {
      "post": {
        "security": [],
        "description": "Create User",
        "tags": [
          "Identity"
        ],
        "operationId": "CreateUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create User Success"
          },
          "400": {
            "description": "Create User Failed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "security": [],
        "description": "User Login",
        "tags": [
          "Identity"
        ],
        "operationId": "Login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Success, return user info.",
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          },
          "401": {
            "description": "Login Failed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/user/logout": {
      "get": {
        "description": "Logout",
        "tags": [
          "Identity"
        ],
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "Logout Success"
          },
          "401": {
            "description": "Logout Failed, no login",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/whoami": {
      "get": {
        "description": "Get Current User's Info",
        "tags": [
          "Identity"
        ],
        "operationId": "Whoami",
        "responses": {
          "200": {
            "description": "Get Current User's Info Success",
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          },
          "401": {
            "description": "Get Current User's Info Failed, no login",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "错误信息",
          "type": "string",
          "example": "error message"
        }
      }
    },
    "Token": {
      "description": "Token Object",
      "type": "object",
      "properties": {
        "create_at": {
          "description": "create at, unix timestamp",
          "type": "integer",
          "example": 1528894200
        },
        "expired_at": {
          "description": "expired at, unix timestamp",
          "type": "integer",
          "example": 1528994200
        },
        "id": {
          "description": "id",
          "type": "integer",
          "example": 1
        },
        "type": {
          "description": "token type",
          "type": "string",
          "enum": [
            "session",
            "private",
            "public"
          ]
        },
        "update_at": {
          "description": "create at, unix timestamp",
          "type": "integer",
          "example": 1528894200
        },
        "user_id": {
          "description": "user's id",
          "type": "integer",
          "example": 1
        },
        "value": {
          "description": "token value",
          "type": "string",
          "example": "zxicgoiuasie"
        }
      }
    },
    "UserInfo": {
      "description": "User's Info",
      "type": "object",
      "properties": {
        "email": {
          "description": "email, unique",
          "type": "string",
          "example": "foo@bar.com"
        },
        "id": {
          "description": "id",
          "type": "integer",
          "example": 1
        },
        "password": {
          "description": "password",
          "type": "string",
          "example": "foobar123"
        },
        "user_name": {
          "description": "user's name, not unique",
          "type": "string",
          "example": "foobar"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "Cookie",
      "in": "header"
    }
  },
  "security": [
    {
      "key": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "apiserver",
    "title": "ez-deploy apiserver.",
    "version": "1.0.0"
  },
  "paths": {
    "/user/create": {
      "post": {
        "security": [],
        "description": "Create User",
        "tags": [
          "Identity"
        ],
        "operationId": "CreateUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create User Success"
          },
          "400": {
            "description": "Create User Failed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "security": [],
        "description": "User Login",
        "tags": [
          "Identity"
        ],
        "operationId": "Login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Success, return user info.",
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          },
          "401": {
            "description": "Login Failed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/user/logout": {
      "get": {
        "description": "Logout",
        "tags": [
          "Identity"
        ],
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "Logout Success"
          },
          "401": {
            "description": "Logout Failed, no login",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/whoami": {
      "get": {
        "description": "Get Current User's Info",
        "tags": [
          "Identity"
        ],
        "operationId": "Whoami",
        "responses": {
          "200": {
            "description": "Get Current User's Info Success",
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          },
          "401": {
            "description": "Get Current User's Info Failed, no login",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "错误信息",
          "type": "string",
          "example": "error message"
        }
      }
    },
    "Token": {
      "description": "Token Object",
      "type": "object",
      "properties": {
        "create_at": {
          "description": "create at, unix timestamp",
          "type": "integer",
          "example": 1528894200
        },
        "expired_at": {
          "description": "expired at, unix timestamp",
          "type": "integer",
          "example": 1528994200
        },
        "id": {
          "description": "id",
          "type": "integer",
          "example": 1
        },
        "type": {
          "description": "token type",
          "type": "string",
          "enum": [
            "session",
            "private",
            "public"
          ]
        },
        "update_at": {
          "description": "create at, unix timestamp",
          "type": "integer",
          "example": 1528894200
        },
        "user_id": {
          "description": "user's id",
          "type": "integer",
          "example": 1
        },
        "value": {
          "description": "token value",
          "type": "string",
          "example": "zxicgoiuasie"
        }
      }
    },
    "UserInfo": {
      "description": "User's Info",
      "type": "object",
      "properties": {
        "email": {
          "description": "email, unique",
          "type": "string",
          "example": "foo@bar.com"
        },
        "id": {
          "description": "id",
          "type": "integer",
          "example": 1
        },
        "password": {
          "description": "password",
          "type": "string",
          "example": "foobar123"
        },
        "user_name": {
          "description": "user's name, not unique",
          "type": "string",
          "example": "foobar"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "Cookie",
      "in": "header"
    }
  },
  "security": [
    {
      "key": []
    }
  ]
}`))
}
