// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTicketReq SSH Pod Ticket Object
//
// swagger:model GetTicketReq
type GetTicketReq struct {

	// pod name
	// Example: foobar-9zqb2
	PodName string `json:"pod_name,omitempty"`

	// project id
	// Example: 1
	ProjectID int64 `json:"project_id,omitempty"`
}

// Validate validates this get ticket req
func (m *GetTicketReq) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get ticket req based on context it is used
func (m *GetTicketReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetTicketReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetTicketReq) UnmarshalBinary(b []byte) error {
	var res GetTicketReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
